In [1]:
import torch


In [30]:
a=torch.tensor([[1.0,2.0,-1.],[2.0,2.0,-1.],[0.,0.,0.]])  #consideriamo i vettori mostrati in output in verticale
print(a)

tensor([[ 1.,  2., -1.],
        [ 2.,  2., -1.],
        [ 0.,  0.,  0.]])


In [6]:
a=torch.tensor([[1.0,2.0],[2.0,2.0],[-1.,-1.]])
print(a)

tensor([[ 1.,  2.],
        [ 2.,  2.],
        [-1., -1.]])


In [32]:
q,r=torch.linalg.qr(a,mode='reduced') 
#quando l'ultima riga di r è tutta 0, 
#vuol dire che quella dimensione di q è inutile per creare i vettori di partenza ->
# vuol dire che i due vettori di prima sono sufficienti, perchè si possono combinare linearmente per ottenere tutti i vettori necessari
print(q)
print(r)

#quindi bisogna leggere il tensore r, e quando si trova una riga con entrambi i numeri uguali a 0, la corrispondente colonna va rimossa. i vettori
#che rimangono, al termine di questa operazione, sono una base dei vettori in input siccome possono essere moltiplicati per dei coefficienti 
#per ottenere i vettori risultato. per cui su questi vettori si può fare le fasi successive

tensor([[-0.4472, -0.8944,  0.0000],
        [-0.8944,  0.4472,  0.0000],
        [-0.0000, -0.0000,  1.0000]])
tensor([[-2.2361, -2.6833,  1.3416],
        [ 0.0000, -0.8944,  0.4472],
        [ 0.0000,  0.0000,  0.0000]])


In [49]:
#vediamo come estrarre 
l = []
eps = 1e-5
#l è la lista degli indici dei vettori utili
for i in range(r.size()[0]):
    if r[i,:].norm() > eps:
        l.append(i)
    

In [50]:
base_ortogonale=q[:,l ]
base_ortogonale
#ECCELLENTE...

tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472],
        [-0.0000, -0.0000]])

In [34]:
q.matmul(r)

tensor([[ 1.0000,  2.0000, -1.0000],
        [ 2.0000,  2.0000, -1.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [29]:
v = torch.tensor([[1.,0.],[1.,1.],[1.,0.]])
print(a)
print(v)
a.matmul(v)

tensor([[ 1.,  2., -1.],
        [ 2.,  2., -1.],
        [ 0.,  0.,  0.]])
tensor([[1., 0.],
        [1., 1.],
        [1., 0.]])


tensor([[2., 2.],
        [3., 2.],
        [0., 0.]])

In [26]:
q[:,1].dot(q[:,1])


tensor(1.0000)

In [1]:
#codice definitivo:
#supponendo che a sia un torch tensor nel quale i vettori sono per colonna
def base_ortogonale(a):
    q,r=torch.linalg.qr(a,mode='reduced') 
    l = []
    eps = 1e-5
    #l è la lista degli indici dei vettori utili
    for i in range(r.size()[0]):
        if r[i,:].norm() > eps:
            l.append(i)
    base_ortogonale=q[:,l ]
    return base_ortogonale

In [10]:
d = torch.tensor([[1.,0.],[2.,9.],[-1.,0.],[3.,3.],[-2.,-2]])
d.T

tensor([[ 1.,  2., -1.,  3., -2.],
        [ 0.,  9.,  0.,  3., -2.]])

In [11]:
base_ortogonale(d.T) #BOOOOOM

tensor([[1., 0.],
        [-0., 1.]])